version: '3'

services:
  mysqldb:
    container_name: mysql_quarkus
    image: mysql:5
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
